In [1]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split

from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.multiclass import OneVsRestClassifier

In [2]:
import sys
!{sys.executable} -m pip install sklearn


[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
df = pd.read_csv('stackoverflow.csv', index_col=0)
df.head()

Text                Tags
2  aspnet site maps has anyone got experience cre...  ['sql', 'asp.net']
4  adding scripting functionality to net applicat...      ['c#', '.net']
5  should i use nested classes in this case i am ...             ['c++']
6  homegrown consumption of web services i have b...            ['.net']
8  automatically update version number i would li...              ['c#']

Tags Col is in Str format we need to convert it into List format

In [4]:
df['Tags'].iloc[0]

"['sql', 'asp.net']"

In [5]:
type(df['Tags'].iloc[0])

str

In [6]:
import ast
ast.literal_eval(df['Tags'].iloc[0])  #converted str to list

['sql', 'asp.net']

In [7]:
df['Tags'] = df['Tags'].apply(lambda x: ast.literal_eval(x))  #conversion for all rows done

In [8]:
df.head()

Text            Tags
2  aspnet site maps has anyone got experience cre...  [sql, asp.net]
4  adding scripting functionality to net applicat...      [c#, .net]
5  should i use nested classes in this case i am ...           [c++]
6  homegrown consumption of web services i have b...          [.net]
8  automatically update version number i would li...            [c#]

One Hot encoding - Multilabelbinarizer allows you to encode multiple labels per instance. It is used when any column has multiple labels

 This is done for the target feature.

In [9]:
y = df['Tags']
y

2          [sql, asp.net]
4              [c#, .net]
5                   [c++]
6                  [.net]
8                    [c#]
                ...      
1262668             [c++]
1262834             [c++]
1262915          [python]
1263065          [python]
1263454             [c++]
Name: Tags, Length: 48976, dtype: object

In [10]:
multilabel = MultiLabelBinarizer()
y = multilabel.fit_transform(df['Tags'])
y

array([[0, 0, 1, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [11]:
multilabel.classes_

array(['.net', 'android', 'asp.net', 'c', 'c#', 'c++', 'css', 'html',
       'ios', 'iphone', 'java', 'javascript', 'jquery', 'mysql',
       'objective-c', 'php', 'python', 'ruby', 'ruby-on-rails', 'sql'],
      dtype=object)

In [12]:
pd.DataFrame(y, columns=multilabel.classes_)

.net  android  asp.net  c  c#  c++  css  html  ios  iphone  java  \
0         0        0        1  0   0    0    0     0    0       0     0   
1         1        0        0  0   1    0    0     0    0       0     0   
2         0        0        0  0   0    1    0     0    0       0     0   
3         1        0        0  0   0    0    0     0    0       0     0   
4         0        0        0  0   1    0    0     0    0       0     0   
...     ...      ...      ... ..  ..  ...  ...   ...  ...     ...   ...   
48971     0        0        0  0   0    1    0     0    0       0     0   
48972     0        0        0  0   0    1    0     0    0       0     0   
48973     0        0        0  0   0    0    0     0    0       0     0   
48974     0        0        0  0   0    0    0     0    0       0     0   
48975     0        0        0  0   0    1    0     0    0       0     0   

       javascript  jquery  mysql  objective-c  php  python  ruby  \
0               0       0      0            0    0       0     0   
1               0       0      0            0    0       0     0   
2               0       0      0            0    0       0     0   
3               0       0      0            0    0       0     0   
4               0       0      0            0    0       0     0   
...           ...     ...    ...          ...  ...     ...   ...   
48971           0       0      0            0    0       0     0   
48972           0       0      0            0    0       0     0   
48973           0       0      0            0    0       1     0   
48974           0       0      0            0    0       1     0   
48975           0       0      0            0    0       0     0   

       ruby-on-rails  sql  
0                  0    1  
1                  0    0  
2                  0    0  
3                  0    0  
4                  0    0  
...              ...  ...  
48971              0    0  
48972              0    0  
48973              0    0  
48974              0    0  
48975              0    0  

[48976 rows x 20 columns]

TF-IDF Vectorizer - for encoding the input features

In [13]:
print(y)

[[0 0 1 ... 0 0 1]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
